1]numpy for array operation
|| 2]pandas for data manipulation and analysis
|| 3]matplotlib and seaborn  for graphical analysis
|| 4]sklearn for machine learning algorithms and techniques
|| 5]statsmodels for statistical analysis
|| 6]scipy for statistical analysis

In [1]:
import numpy as np

In [33]:
j = [4,6,2,8,9,5]

In [34]:
np.array(j) #array conversion 

array([4, 6, 2, 8, 9, 5])

In [35]:
d = np.array(j)

In [36]:
d

array([4, 6, 2, 8, 9, 5])

In [37]:
type(d)

numpy.ndarray

In [38]:
d.shape #size of the array

(6,)

In [39]:
d.ndim #ndim stands for dimension of the array like 1d,2d ettc..

1

In [40]:
d.size

6

In [52]:
h = d.reshape(2,3)  #while reshape we need to take care for the size , after reshape the size of the array must same

In [54]:
h.ndim  #two dimension

2

In [56]:
# f = d.reshape()

ValueError: cannot reshape array of size 6 into shape (2,2,1)

In [60]:
s = [[1,5,8,3],[2,4,8,3],[2,12,10,3],[5,3,4,9],[9,3,4,5]]
s

[[1, 5, 8, 3], [2, 4, 8, 3], [2, 12, 10, 3], [5, 3, 4, 9], [9, 3, 4, 5]]

In [61]:
type(s)

list

In [62]:
f = np.array(s)
f

array([[ 1,  5,  8,  3],
       [ 2,  4,  8,  3],
       [ 2, 12, 10,  3],
       [ 5,  3,  4,  9],
       [ 9,  3,  4,  5]])

In [63]:
f.shape

(5, 4)

In [64]:
f.size

20

In [65]:
f.ndim

2

In [66]:
s

[[1, 5, 8, 3], [2, 4, 8, 3], [2, 12, 10, 3], [5, 3, 4, 9], [9, 3, 4, 5]]

In [69]:
f.reshape(5,2,2)

array([[[ 1,  5],
        [ 8,  3]],

       [[ 2,  4],
        [ 8,  3]],

       [[ 2, 12],
        [10,  3]],

       [[ 5,  3],
        [ 4,  9]],

       [[ 9,  3],
        [ 4,  5]]])

In [70]:
f.reshape(2,5,2)

array([[[ 1,  5],
        [ 8,  3],
        [ 2,  4],
        [ 8,  3],
        [ 2, 12]],

       [[10,  3],
        [ 5,  3],
        [ 4,  9],
        [ 9,  3],
        [ 4,  5]]])

In [71]:
f.reshape(2,2,5)

array([[[ 1,  5,  8,  3,  2],
        [ 4,  8,  3,  2, 12]],

       [[10,  3,  5,  3,  4],
        [ 9,  9,  3,  4,  5]]])

In [72]:
z = f.reshape(5,2,2)

In [73]:
z.ndim

3

In [74]:
z.shape

(5, 2, 2)

In [75]:
z.size

20

In [78]:
y = f.reshape(20,)
y

array([ 1,  5,  8,  3,  2,  4,  8,  3,  2, 12, 10,  3,  5,  3,  4,  9,  9,
        3,  4,  5])

In [79]:
y.shape

(20,)

In [80]:
y.ndim

1

In [81]:
o = f.reshape(20,1)
o

array([[ 1],
       [ 5],
       [ 8],
       [ 3],
       [ 2],
       [ 4],
       [ 8],
       [ 3],
       [ 2],
       [12],
       [10],
       [ 3],
       [ 5],
       [ 3],
       [ 4],
       [ 9],
       [ 9],
       [ 3],
       [ 4],
       [ 5]])

In [82]:
o.ndim

2

In [87]:
p = f.reshape(1,1,20)
p

array([[[ 1,  5,  8,  3,  2,  4,  8,  3,  2, 12, 10,  3,  5,  3,  4,  9,
          9,  3,  4,  5]]])

In [88]:
q = f.reshape(2,2,1,5)

In [89]:
q

array([[[[ 1,  5,  8,  3,  2]],

        [[ 4,  8,  3,  2, 12]]],


       [[[10,  3,  5,  3,  4]],

        [[ 9,  9,  3,  4,  5]]]])

In [90]:
q.ndim

4

In [104]:
l = (3,4,5,6)

In [105]:
l

(3, 4, 5, 6)

In [112]:
tuple(range(1,20)) #print the value (starting,end-1,skip)

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19)

In [114]:
tuple(range(1,600,100))

(1, 101, 201, 301, 401, 501)

In [118]:
set(range(-1,-11,-1))

{-10, -9, -8, -7, -6, -5, -4, -3, -2, -1}

In [119]:
tuple(range(2.5,5,0.5))  #name function only work in integer (int)

TypeError: 'float' object cannot be interpreted as an integer

In [121]:
np.arange(2.5,5,0.5) # by using numpy we can use float 

array([2.5, 3. , 3.5, 4. , 4.5])

In [122]:
range(5,10)

range(5, 10)

In [124]:
for i in range(5,10):
    print("data" , i)

data 5
data 6
data 7
data 8
data 9


In [127]:
u = [5,87,23,46,62,84,80,45,77,33,80]
u

[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]

In [138]:
x=[]
y=[]
for i in range(len(u)):# to itrate over the position we use len
    if i%2==0:
        x.append(u[i])
    else:
        y.append(u[i])

In [139]:
for i in range(len(u)):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
