In [64]:
import numpy as np
import pandas as pd
import seaborn as sns

In [10]:
k = [4,2.56789,9,87.9999,40,'hyderadad']


In [11]:
k

[4, 2.56789, 9, 87.9999, 40, 'hyderadad']

In [12]:
pd.Series(k)

0            4
1      2.56789
2            9
3      87.9999
4           40
5    hyderadad
dtype: object

In [13]:
a = np.random.randint(20,40,(1,15))

In [14]:
a

array([[26, 34, 36, 35, 29, 24, 25, 31, 33, 23, 21, 31, 38, 30, 26]])

In [15]:
a.ndim

2

In [16]:
b= np.random.randint(20,40,15)

In [17]:
b

array([20, 32, 20, 29, 37, 37, 25, 25, 37, 32, 20, 36, 24, 21, 39])

In [18]:
pd.Series(b)

0     20
1     32
2     20
3     29
4     37
5     37
6     25
7     25
8     37
9     32
10    20
11    36
12    24
13    21
14    39
dtype: int32

In [19]:
s=pd.Series(b)

In [20]:
s

0     20
1     32
2     20
3     29
4     37
5     37
6     25
7     25
8     37
9     32
10    20
11    36
12    24
13    21
14    39
dtype: int32

In [21]:
s[4]

37

In [22]:
s[4:15:6]

4     37
10    20
dtype: int32

In [23]:
b = np.random.randint(100,200,(6,5))

In [24]:
b.ndim

2

In [25]:
b

array([[191, 119, 199, 111, 186],
       [107, 156, 174, 163, 100],
       [143, 150, 129, 158, 151],
       [153, 108, 173, 150, 199],
       [195, 175, 101, 146, 174],
       [166, 159, 131, 175, 184]])

In [26]:
b.shape

(6, 5)

In [27]:
df = pd.DataFrame(b,columns=['roll','name','age','adds','country'])
df

roll  name  age  adds  country
0   191   119  199   111      186
1   107   156  174   163      100
2   143   150  129   158      151
3   153   108  173   150      199
4   195   175  101   146      174
5   166   159  131   175      184

In [28]:
df = pd.DataFrame(b,columns=['roll','name','age','adds','country'],index=[101,102,103,104,105,106])
df

roll  name  age  adds  country
101   191   119  199   111      186
102   107   156  174   163      100
103   143   150  129   158      151
104   153   108  173   150      199
105   195   175  101   146      174
106   166   159  131   175      184

In [29]:

df.iloc[0]

roll       191
name       119
age        199
adds       111
country    186
Name: 101, dtype: int32

In [30]:
df.loc[101]

roll       191
name       119
age        199
adds       111
country    186
Name: 101, dtype: int32

In [31]:
df.iloc[0,0]

191

In [32]:
df.loc[101,'age']

199

In [33]:

df.loc[101,['name','age']]

name    119
age     199
Name: 101, dtype: int32

In [34]:
df.iloc[0,1:3]

name    119
age     199
Name: 101, dtype: int32

In [35]:
df

roll  name  age  adds  country
101   191   119  199   111      186
102   107   156  174   163      100
103   143   150  129   158      151
104   153   108  173   150      199
105   195   175  101   146      174
106   166   159  131   175      184

In [36]:
df.iloc[[3,4]]

roll  name  age  adds  country
104   153   108  173   150      199
105   195   175  101   146      174

In [37]:
df.age

101    199
102    174
103    129
104    173
105    101
106    131
Name: age, dtype: int32

In [38]:
df[['name','age']]

name  age
101   119  199
102   156  174
103   150  129
104   108  173
105   175  101
106   159  131

In [39]:
df.loc[[101,102,103],['roll','name','age']]

roll  name  age
101   191   119  199
102   107   156  174
103   143   150  129

In [67]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [68]:
sns.load_dataset('taxis')

pickup             dropoff  passengers  distance  fare  \
0    2019-03-23 20:21:09 2019-03-23 20:27:24           1      1.60   7.0   
1    2019-03-04 16:11:55 2019-03-04 16:19:00           1      0.79   5.0   
2    2019-03-27 17:53:01 2019-03-27 18:00:25           1      1.37   7.5   
3    2019-03-10 01:23:59 2019-03-10 01:49:51           1      7.70  27.0   
4    2019-03-30 13:27:42 2019-03-30 13:37:14           3      2.16   9.0   
...                  ...                 ...         ...       ...   ...   
6428 2019-03-31 09:51:53 2019-03-31 09:55:27           1      0.75   4.5   
6429 2019-03-31 17:38:00 2019-03-31 18:34:23           1     18.74  58.0   
6430 2019-03-23 22:55:18 2019-03-23 23:14:25           1      4.14  16.0   
6431 2019-03-04 10:09:25 2019-03-04 10:14:29           1      1.12   6.0   
6432 2019-03-13 19:31:22 2019-03-13 19:48:02           1      3.85  15.0   

       tip  tolls  total   color      payment            pickup_zone  \
0     2.15    0.0  12.95  yellow  credit card        Lenox Hill West   
1     0.00    0.0   9.30  yellow         cash  Upper West Side South   
2     2.36    0.0  14.16  yellow  credit card          Alphabet City   
3     6.15    0.0  36.95  yellow  credit card              Hudson Sq   
4     1.10    0.0  13.40  yellow  credit card           Midtown East   
...    ...    ...    ...     ...          ...                    ...   
6428  1.06    0.0   6.36   green  credit card      East Harlem North   
6429  0.00    0.0  58.80   green  credit card                Jamaica   
6430  0.00    0.0  17.30   green         cash    Crown Heights North   
6431  0.00    0.0   6.80   green  credit card          East New York   
6432  3.36    0.0  20.16   green  credit card            Boerum Hill   

                          dropoff_zone pickup_borough dropoff_borough  
0                  UN/Turtle Bay South      Manhattan       Manhattan  
1                Upper West Side South      Manhattan       Manhattan  
2                         West Village      Manhattan       Manhattan  
3                       Yorkville West      Manhattan       Manhattan  
4                       Yorkville West      Manhattan       Manhattan  
...                                ...            ...             ...  
6428              Central Harlem North      Manhattan       Manhattan  
6429  East Concourse/Concourse Village         Queens           Bronx  
6430                    Bushwick North       Brooklyn        Brooklyn  
6431      East Flatbush/Remsen Village       Brooklyn        Brooklyn  
6432                   Windsor Terrace       Brooklyn        Brooklyn  

[6433 rows x 14 columns]

In [69]:
df = sns.load_dataset('taxis')

In [70]:
df

pickup             dropoff  passengers  distance  fare  \
0    2019-03-23 20:21:09 2019-03-23 20:27:24           1      1.60   7.0   
1    2019-03-04 16:11:55 2019-03-04 16:19:00           1      0.79   5.0   
2    2019-03-27 17:53:01 2019-03-27 18:00:25           1      1.37   7.5   
3    2019-03-10 01:23:59 2019-03-10 01:49:51           1      7.70  27.0   
4    2019-03-30 13:27:42 2019-03-30 13:37:14           3      2.16   9.0   
...                  ...                 ...         ...       ...   ...   
6428 2019-03-31 09:51:53 2019-03-31 09:55:27           1      0.75   4.5   
6429 2019-03-31 17:38:00 2019-03-31 18:34:23           1     18.74  58.0   
6430 2019-03-23 22:55:18 2019-03-23 23:14:25           1      4.14  16.0   
6431 2019-03-04 10:09:25 2019-03-04 10:14:29           1      1.12   6.0   
6432 2019-03-13 19:31:22 2019-03-13 19:48:02           1      3.85  15.0   

       tip  tolls  total   color      payment            pickup_zone  \
0     2.15    0.0  12.95  yellow  credit card        Lenox Hill West   
1     0.00    0.0   9.30  yellow         cash  Upper West Side South   
2     2.36    0.0  14.16  yellow  credit card          Alphabet City   
3     6.15    0.0  36.95  yellow  credit card              Hudson Sq   
4     1.10    0.0  13.40  yellow  credit card           Midtown East   
...    ...    ...    ...     ...          ...                    ...   
6428  1.06    0.0   6.36   green  credit card      East Harlem North   
6429  0.00    0.0  58.80   green  credit card                Jamaica   
6430  0.00    0.0  17.30   green         cash    Crown Heights North   
6431  0.00    0.0   6.80   green  credit card          East New York   
6432  3.36    0.0  20.16   green  credit card            Boerum Hill   

                          dropoff_zone pickup_borough dropoff_borough  
0                  UN/Turtle Bay South      Manhattan       Manhattan  
1                Upper West Side South      Manhattan       Manhattan  
2                         West Village      Manhattan       Manhattan  
3                       Yorkville West      Manhattan       Manhattan  
4                       Yorkville West      Manhattan       Manhattan  
...                                ...            ...             ...  
6428              Central Harlem North      Manhattan       Manhattan  
6429  East Concourse/Concourse Village         Queens           Bronx  
6430                    Bushwick North       Brooklyn        Brooklyn  
6431      East Flatbush/Remsen Village       Brooklyn        Brooklyn  
6432                   Windsor Terrace       Brooklyn        Brooklyn  

[6433 rows x 14 columns]

In [71]:
df['color'].isnull().sum()

0

In [72]:
df['payment'].isnull().sum()

44

In [73]:

df.isnull().sum()

pickup              0
dropoff             0
passengers          0
distance            0
fare                0
tip                 0
tolls               0
total               0
color               0
payment            44
pickup_zone        26
dropoff_zone       45
pickup_borough     26
dropoff_borough    45
dtype: int64

In [74]:
(44/6433)*100
#percentage


0.6839732628633608

In [75]:
df.shape[0]

6433

In [76]:
(df.isnull().sum()/df.shape[0])*100

pickup             0.000000
dropoff            0.000000
passengers         0.000000
distance           0.000000
fare               0.000000
tip                0.000000
tolls              0.000000
total              0.000000
color              0.000000
payment            0.683973
pickup_zone        0.404166
dropoff_zone       0.699518
pickup_borough     0.404166
dropoff_borough    0.699518
dtype: float64

missing data handling
1) imputation(fill in the blanks)
    1)stastical measures
    2)parameter
   
2)delete data
    rows
    columns

In [77]:
df.drop('pickup_zone',axis=1,inplace=True) # to delete colum:inplace is used to delete column or ROw permanently

In [78]:
df

pickup             dropoff  passengers  distance  fare  \
0    2019-03-23 20:21:09 2019-03-23 20:27:24           1      1.60   7.0   
1    2019-03-04 16:11:55 2019-03-04 16:19:00           1      0.79   5.0   
2    2019-03-27 17:53:01 2019-03-27 18:00:25           1      1.37   7.5   
3    2019-03-10 01:23:59 2019-03-10 01:49:51           1      7.70  27.0   
4    2019-03-30 13:27:42 2019-03-30 13:37:14           3      2.16   9.0   
...                  ...                 ...         ...       ...   ...   
6428 2019-03-31 09:51:53 2019-03-31 09:55:27           1      0.75   4.5   
6429 2019-03-31 17:38:00 2019-03-31 18:34:23           1     18.74  58.0   
6430 2019-03-23 22:55:18 2019-03-23 23:14:25           1      4.14  16.0   
6431 2019-03-04 10:09:25 2019-03-04 10:14:29           1      1.12   6.0   
6432 2019-03-13 19:31:22 2019-03-13 19:48:02           1      3.85  15.0   

       tip  tolls  total   color      payment  \
0     2.15    0.0  12.95  yellow  credit card   
1     0.00    0.0   9.30  yellow         cash   
2     2.36    0.0  14.16  yellow  credit card   
3     6.15    0.0  36.95  yellow  credit card   
4     1.10    0.0  13.40  yellow  credit card   
...    ...    ...    ...     ...          ...   
6428  1.06    0.0   6.36   green  credit card   
6429  0.00    0.0  58.80   green  credit card   
6430  0.00    0.0  17.30   green         cash   
6431  0.00    0.0   6.80   green  credit card   
6432  3.36    0.0  20.16   green  credit card   

                          dropoff_zone pickup_borough dropoff_borough  
0                  UN/Turtle Bay South      Manhattan       Manhattan  
1                Upper West Side South      Manhattan       Manhattan  
2                         West Village      Manhattan       Manhattan  
3                       Yorkville West      Manhattan       Manhattan  
4                       Yorkville West      Manhattan       Manhattan  
...                                ...            ...             ...  
6428              Central Harlem North      Manhattan       Manhattan  
6429  East Concourse/Concourse Village         Queens           Bronx  
6430                    Bushwick North       Brooklyn        Brooklyn  
6431      East Flatbush/Remsen Village       Brooklyn        Brooklyn  
6432                   Windsor Terrace       Brooklyn        Brooklyn  

[6433 rows x 13 columns]

In [81]:
df.drop([2,3,6432,6430],axis=0,inplace=True)

In [82]:
df

pickup             dropoff  passengers  distance  fare  \
0    2019-03-23 20:21:09 2019-03-23 20:27:24           1      1.60   7.0   
1    2019-03-04 16:11:55 2019-03-04 16:19:00           1      0.79   5.0   
4    2019-03-30 13:27:42 2019-03-30 13:37:14           3      2.16   9.0   
5    2019-03-11 10:37:23 2019-03-11 10:47:31           1      0.49   7.5   
6    2019-03-26 21:07:31 2019-03-26 21:17:29           1      3.65  13.0   
...                  ...                 ...         ...       ...   ...   
6426 2019-03-28 08:04:47 2019-03-28 08:07:46           1      0.71   4.5   
6427 2019-03-23 18:26:09 2019-03-23 18:49:12           1      7.07  20.0   
6428 2019-03-31 09:51:53 2019-03-31 09:55:27           1      0.75   4.5   
6429 2019-03-31 17:38:00 2019-03-31 18:34:23           1     18.74  58.0   
6431 2019-03-04 10:09:25 2019-03-04 10:14:29           1      1.12   6.0   

       tip  tolls  total   color      payment  \
0     2.15    0.0  12.95  yellow  credit card   
1     0.00    0.0   9.30  yellow         cash   
4     1.10    0.0  13.40  yellow  credit card   
5     2.16    0.0  12.96  yellow  credit card   
6     2.00    0.0  18.80  yellow  credit card   
...    ...    ...    ...     ...          ...   
6426  0.50    0.0   5.80   green  credit card   
6427  0.00    0.0  20.00   green         cash   
6428  1.06    0.0   6.36   green  credit card   
6429  0.00    0.0  58.80   green  credit card   
6431  0.00    0.0   6.80   green  credit card   

                          dropoff_zone pickup_borough dropoff_borough  
0                  UN/Turtle Bay South      Manhattan       Manhattan  
1                Upper West Side South      Manhattan       Manhattan  
4                       Yorkville West      Manhattan       Manhattan  
5                         Midtown East      Manhattan       Manhattan  
6              Two Bridges/Seward Park      Manhattan       Manhattan  
...                                ...            ...             ...  
6426             Upper West Side North      Manhattan       Manhattan  
6427                 East Harlem South          Bronx       Manhattan  
6428              Central Harlem North      Manhattan       Manhattan  
6429  East Concourse/Concourse Village         Queens           Bronx  
6431      East Flatbush/Remsen Village       Brooklyn        Brooklyn  

[6429 rows x 13 columns]

In [85]:
np.random.randint(10,50,15)

array([42, 33, 23, 15, 24, 14, 39, 32, 35, 32, 21, 11, 17, 48, 13])

In [86]:
a=np.random.randint(10,50,15)

In [87]:
a

array([31, 31, 44, 12, 34, 44, 35, 13, 13, 49, 12, 32, 12, 25, 28])

In [88]:
a[a>40]

array([44, 44, 49])

In [89]:
df.iloc[100]

pickup               2019-03-01 07:34:30
dropoff              2019-03-01 07:40:58
passengers                             1
distance                             1.2
fare                                 6.5
tip                                  0.0
tolls                                0.0
total                                9.8
color                             yellow
payment                             cash
dropoff_zone       Upper West Side North
pickup_borough                 Manhattan
dropoff_borough                Manhattan
Name: 102, dtype: object

In [90]:
df[df['color']=='green']

pickup             dropoff  passengers  distance  fare  \
5451 2019-03-24 15:05:22 2019-03-24 15:26:32           1      2.29  15.0   
5452 2019-03-14 22:04:04 2019-03-14 22:10:00           1      0.80   5.5   
5453 2019-03-29 18:12:27 2019-03-29 18:20:40           1      1.51   7.5   
5454 2019-03-06 11:11:33 2019-03-06 11:15:15           1      0.45   4.5   
5455 2019-03-04 18:43:53 2019-03-04 18:46:50           1      0.61   4.0   
...                  ...                 ...         ...       ...   ...   
6426 2019-03-28 08:04:47 2019-03-28 08:07:46           1      0.71   4.5   
6427 2019-03-23 18:26:09 2019-03-23 18:49:12           1      7.07  20.0   
6428 2019-03-31 09:51:53 2019-03-31 09:55:27           1      0.75   4.5   
6429 2019-03-31 17:38:00 2019-03-31 18:34:23           1     18.74  58.0   
6431 2019-03-04 10:09:25 2019-03-04 10:14:29           1      1.12   6.0   

       tip  tolls  total  color      payment  \
5451  0.00    0.0  15.80  green         cash   
5452  0.00    0.0   6.80  green  credit card   
5453  1.20    0.0  10.50  green  credit card   
5454  0.00    0.0   5.30  green         cash   
5455  0.00    0.0   5.80  green         cash   
...    ...    ...    ...    ...          ...   
6426  0.50    0.0   5.80  green  credit card   
6427  0.00    0.0  20.00  green         cash   
6428  1.06    0.0   6.36  green  credit card   
6429  0.00    0.0  58.80  green  credit card   
6431  0.00    0.0   6.80  green  credit card   

                          dropoff_zone pickup_borough dropoff_borough  
5451                            Corona         Queens          Queens  
5452                       Kew Gardens         Queens          Queens  
5453                 East Harlem South      Manhattan       Manhattan  
5454                 East Harlem South      Manhattan       Manhattan  
5455                   Carroll Gardens       Brooklyn        Brooklyn  
...                                ...            ...             ...  
6426             Upper West Side North      Manhattan       Manhattan  
6427                 East Harlem South          Bronx       Manhattan  
6428              Central Harlem North      Manhattan       Manhattan  
6429  East Concourse/Concourse Village         Queens           Bronx  
6431      East Flatbush/Remsen Village       Brooklyn        Brooklyn  

[980 rows x 13 columns]

In [93]:
df[df['total']==15]

pickup             dropoff  passengers  distance  fare  tip  \
1555 2019-03-20 12:55:52 2019-03-20 13:07:00           1      2.74  10.5  1.2   
2356 2019-03-21 08:13:04 2019-03-21 08:53:41           1      1.50  10.5  1.2   
3844 2019-03-11 07:08:42 2019-03-11 07:21:38           1      2.40  11.0  0.7   

      tolls  total   color      payment               dropoff_zone  \
1555    0.0   15.0  yellow  credit card        Morningside Heights   
2356    0.0   15.0  yellow  credit card  Times Sq/Theatre District   
3844    0.0   15.0  yellow  credit card  Times Sq/Theatre District   

     pickup_borough dropoff_borough  
1555      Manhattan       Manhattan  
2356      Manhattan       Manhattan  
3844      Manhattan       Manhattan

In [96]:
df[df['payment']=='cash']

pickup             dropoff  passengers  distance  fare  tip  \
1    2019-03-04 16:11:55 2019-03-04 16:19:00           1      0.79   5.0  0.0   
10   2019-03-16 10:02:25 2019-03-16 10:22:29           1      3.90  17.0  0.0   
13   2019-03-19 07:55:25 2019-03-19 08:09:17           1      1.75  10.5  0.0   
14   2019-03-27 12:13:34 2019-03-27 12:25:48           0      2.90  11.5  0.0   
15   2019-03-16 17:53:34 2019-03-16 18:13:57           3      2.09  13.5  0.0   
...                  ...                 ...         ...       ...   ...  ...   
6419 2019-03-16 10:37:52 2019-03-16 10:47:33           1      1.54   8.5  0.0   
6420 2019-03-16 15:39:23 2019-03-16 15:46:18           2      1.20   7.0  0.0   
6422 2019-03-22 20:17:35 2019-03-22 20:36:07           1      4.02  16.0  0.0   
6424 2019-03-30 20:52:15 2019-03-30 20:59:55           1      1.70   8.0  0.0   
6427 2019-03-23 18:26:09 2019-03-23 18:49:12           1      7.07  20.0  0.0   

      tolls  total   color payment                dropoff_zone pickup_borough  \
1       0.0    9.3  yellow    cash       Upper West Side South      Manhattan   
10      0.0   17.8  yellow    cash                     Astoria         Queens   
13      0.0   13.8  yellow    cash   Times Sq/Theatre District      Manhattan   
14      0.0   14.8  yellow    cash     Two Bridges/Seward Park      Manhattan   
15      0.0   16.8  yellow    cash                Clinton East      Manhattan   
...     ...    ...     ...     ...                         ...            ...   
6419    0.0    9.3   green    cash                      Inwood      Manhattan   
6420    0.0    7.8   green    cash       Upper West Side North      Manhattan   
6422    0.0   17.3   green    cash  Spuyten Duyvil/Kingsbridge      Manhattan   
6424    0.0    9.3   green    cash        Central Harlem North      Manhattan   
6427    0.0   20.0   green    cash           East Harlem South          Bronx   

     dropoff_borough  
1          Manhattan  
10            Queens  
13         Manhattan  
14         Manhattan  
15         Manhattan  
...              ...  
6419       Manhattan  
6420       Manhattan  
6422           Bronx  
6424       Manhattan  
6427       Manhattan  

[1811 rows x 13 columns]

In [97]:
df['payment']=='cash'

0       False
1        True
4       False
5       False
6       False
        ...  
6426    False
6427     True
6428    False
6429    False
6431    False
Name: payment, Length: 6429, dtype: bool

In [103]:
df[(df['payment']=='cash')&(df['total']>15)]

pickup             dropoff  passengers  distance  fare  tip  \
10   2019-03-16 10:02:25 2019-03-16 10:22:29           1      3.90  17.0  0.0   
15   2019-03-16 17:53:34 2019-03-16 18:13:57           3      2.09  13.5  0.0   
16   2019-03-15 12:36:05 2019-03-15 12:54:28           1      2.12  13.0  0.0   
26   2019-03-03 02:45:36 2019-03-03 03:02:14           1      3.35  13.5  0.0   
29   2019-03-06 08:09:03 2019-03-06 08:27:11           1      0.92  12.0  0.0   
...                  ...                 ...         ...       ...   ...  ...   
6405 2019-03-21 18:28:55 2019-03-21 18:51:08           2      3.88  16.5  0.0   
6407 2019-03-07 16:35:42 2019-03-07 16:50:03           1      2.68  12.0  0.0   
6408 2019-03-04 07:27:58 2019-03-04 07:49:25           1      6.48  22.0  0.0   
6422 2019-03-22 20:17:35 2019-03-22 20:36:07           1      4.02  16.0  0.0   
6427 2019-03-23 18:26:09 2019-03-23 18:49:12           1      7.07  20.0  0.0   

      tolls  total   color payment                   dropoff_zone  \
10      0.0  17.80  yellow    cash                        Astoria   
15      0.0  16.80  yellow    cash                   Clinton East   
16      0.0  16.30  yellow    cash  Meatpacking/West Village West   
26      0.0  17.30  yellow    cash                        Seaport   
29      0.0  15.30  yellow    cash               Garment District   
...     ...    ...     ...     ...                            ...   
6405    0.0  18.30   green    cash                     Ocean Hill   
6407    0.0  16.55   green    cash          Upper East Side North   
6408    0.0  25.55   green    cash                   Clinton East   
6422    0.0  17.30   green    cash     Spuyten Duyvil/Kingsbridge   
6427    0.0  20.00   green    cash              East Harlem South   

     pickup_borough dropoff_borough  
10           Queens          Queens  
15        Manhattan       Manhattan  
16        Manhattan       Manhattan  
26        Manhattan       Manhattan  
29        Manhattan       Manhattan  
...             ...             ...  
6405       Brooklyn        Brooklyn  
6407      Manhattan       Manhattan  
6408      Manhattan       Manhattan  
6422      Manhattan           Bronx  
6427          Bronx       Manhattan  

[532 rows x 13 columns]