In [1]:
import numpy as np
#import pandas as pd

In [2]:
a = np.random.randint(30,50,15)

In [3]:
a

array([40, 32, 45, 46, 41, 47, 43, 49, 41, 33, 38, 40, 46, 35, 49])

In [4]:
a.ndim

1

In [5]:
a[10]

38

In [6]:
a[4:15]

array([41, 47, 43, 49, 41, 33, 38, 40, 46, 35, 49])

In [9]:
a[-2:-9:-1]

array([35, 46, 40, 38, 33, 41, 49])

In [10]:
np.random.seed(94)
b=np.random.randint(45,78,(7,8))

In [11]:
b

array([[63, 45, 48, 67, 74, 64, 61, 53],
       [61, 59, 55, 77, 69, 69, 48, 60],
       [71, 56, 51, 58, 59, 47, 68, 77],
       [46, 45, 52, 74, 65, 53, 60, 55],
       [64, 72, 46, 69, 65, 75, 75, 51],
       [75, 67, 53, 77, 60, 67, 67, 47],
       [75, 54, 74, 69, 54, 64, 52, 61]])

In [12]:
b[2]  #row access

array([71, 56, 51, 58, 59, 47, 68, 77])

In [13]:
b[2][2] #accession the value

51

In [14]:
b[:,3]  #column

array([67, 77, 58, 74, 69, 77, 69])

In [15]:
b[2,2]  #accessing the row

51

In [19]:
b[1:4]  # accessing  the one or more row 

array([[61, 59, 55, 77, 69, 69, 48, 60],
       [71, 56, 51, 58, 59, 47, 68, 77],
       [46, 45, 52, 74, 65, 53, 60, 55]])

In [20]:
b[1:4,1] # accessing the elemets in that column

array([59, 56, 45])

In [21]:
b[1:4,1:5] # we can access the sub rows also

array([[59, 55, 77, 69],
       [56, 51, 58, 59],
       [45, 52, 74, 65]])

In [24]:
b

array([[63, 45, 48, 67, 74, 64, 61, 53],
       [61, 59, 55, 77, 69, 69, 48, 60],
       [71, 56, 51, 58, 59, 47, 68, 77],
       [46, 45, 52, 74, 65, 53, 60, 55],
       [64, 72, 46, 69, 65, 75, 75, 51],
       [75, 67, 53, 77, 60, 67, 67, 47],
       [75, 54, 74, 69, 54, 64, 52, 61]])

In [29]:
b[3:7,2:7]

array([[52, 74, 65, 53, 60],
       [46, 69, 65, 75, 75],
       [53, 77, 60, 67, 67],
       [74, 69, 54, 64, 52]])

In [32]:
b[3:7,2:7]

array([[52, 74, 65, 53, 60],
       [46, 69, 65, 75, 75],
       [53, 77, 60, 67, 67],
       [74, 69, 54, 64, 52]])

In [35]:
b[1:7,1:7]

array([[59, 55, 77, 69, 69, 48],
       [56, 51, 58, 59, 47, 68],
       [45, 52, 74, 65, 53, 60],
       [72, 46, 69, 65, 75, 75],
       [67, 53, 77, 60, 67, 67],
       [54, 74, 69, 54, 64, 52]])

In [37]:
b

array([[63, 45, 48, 67, 74, 64, 61, 53],
       [61, 59, 55, 77, 69, 69, 48, 60],
       [71, 56, 51, 58, 59, 47, 68, 77],
       [46, 45, 52, 74, 65, 53, 60, 55],
       [64, 72, 46, 69, 65, 75, 75, 51],
       [75, 67, 53, 77, 60, 67, 67, 47],
       [75, 54, 74, 69, 54, 64, 52, 61]])

In [39]:
b:[]

array([[45, 48, 67, 74, 64],
       [59, 55, 77, 69, 69],
       [56, 51, 58, 59, 47],
       [45, 52, 74, 65, 53],
       [72, 46, 69, 65, 75]])

In [44]:
b[2:6,2:5]

array([[51, 58, 59],
       [52, 74, 65],
       [46, 69, 65],
       [53, 77, 60]])

In [46]:
b[(1:7,1:8),1]   #i need to access the 

SyntaxError: invalid syntax (399896044.py, line 1)

In [47]:
b[0:4,1:7]  #for this type of problem first write the row then the ending of the row and in the last write starting of columns and end of column

array([[45, 48, 67, 74, 64, 61],
       [59, 55, 77, 69, 69, 48],
       [56, 51, 58, 59, 47, 68],
       [45, 52, 74, 65, 53, 60]])

In [49]:
import numpy as np
b[b<50]

array([45, 48, 48, 47, 46, 45, 46, 47])

In [50]:
np.where(b<50) # give the row/colums to access the index

(array([0, 0, 1, 2, 3, 3, 4, 5], dtype=int64),
 array([1, 2, 6, 5, 0, 1, 2, 7], dtype=int64))