In [5]:
import numpy as np
ten_strd = np.random.randint(15,18,(20))  #random number (starting , ending-1,numbers of)
ten_strd

array([16, 17, 17, 17, 15, 17, 17, 16, 16, 15, 16, 15, 16, 15, 16, 17, 16,
       16, 17, 15])

In [6]:
ten_strd+.0

array([16., 17., 17., 17., 15., 17., 17., 16., 16., 15., 16., 15., 16.,
       15., 16., 17., 16., 16., 17., 15.])

In [7]:
arr = np.random.randint(20,99,(6,7))  #rows and columns

In [8]:
arr

array([[90, 23, 85, 52, 86, 26, 45],
       [60, 92, 32, 36, 21, 32, 43],
       [79, 57, 87, 29, 50, 30, 28],
       [34, 70, 96, 24, 30, 67, 50],
       [39, 56, 63, 28, 70, 56, 30],
       [75, 29, 85, 27, 71, 34, 70]])

In [9]:
#np.random.seed(234)        #seed used to generate the same data as many times ----- it is called locking the data
array = np.random.randint(20,99,(6,7))
array

array([[24, 40, 39, 36, 92, 80, 29],
       [79, 72, 88, 68, 20, 41, 90],
       [73, 45, 68, 74, 67, 80, 74],
       [45, 39, 33, 22, 97, 62, 57],
       [45, 48, 21, 80, 39, 36, 63],
       [36, 51, 30, 53, 91, 75, 92]])

In [10]:
array

array([[24, 40, 39, 36, 92, 80, 29],
       [79, 72, 88, 68, 20, 41, 90],
       [73, 45, 68, 74, 67, 80, 74],
       [45, 39, 33, 22, 97, 62, 57],
       [45, 48, 21, 80, 39, 36, 63],
       [36, 51, 30, 53, 91, 75, 92]])

In [11]:
arr.ndim

2

In [12]:
arr.size

42

In [13]:
m = [5,20,10,6,8]
m

[5, 20, 10, 6, 8]

In [14]:
square_list = [i*i for i in m]
square_list

[25, 400, 100, 36, 64]

In [15]:
for i in range(len(m)):
   m[i] = m[i]**2

In [2]:
b = (3,5,9,8,1)
b

(3, 5, 9, 8, 1)

In [5]:
lt = tuple(i+5 for i in b)
lt

(8, 10, 14, 13, 6)

In [8]:
k = [55,25,85,75,35,45,95]
k

[55, 25, 85, 75, 35, 45, 95]

In [11]:
v=[]
c=[]
for i in k:
    if i<50:
        v.append(i)
    

In [12]:
print(v)

[25, 35, 45]


In [15]:
import numpy as np
Array = np.random.randint(20,90,10)

In [16]:
Array

array([85, 42, 62, 78, 21, 88, 77, 55, 72, 37])

In [18]:
Array+5  # no need to iterate over the array 

array([90, 47, 67, 83, 26, 93, 82, 60, 77, 42])

In [20]:
Array>50   #it print in the form of boolean

array([ True, False,  True,  True, False,  True,  True,  True,  True,
       False])

In [25]:
Array[Array>50]  # it return thr values which are gratre the 50

array([85, 62, 78, 88, 77, 55, 72])