In [2]:
import pandas as pd
import numpy as np

In [5]:
a=np.random.randint(30,50,15)

In [6]:
a

array([30, 40, 44, 36, 32, 34, 37, 32, 36, 45, 38, 47, 34, 47, 49])

In [7]:
a.ndim

1

In [8]:
a[-2:-10:-1]

array([47, 34, 47, 38, 45, 36, 32, 37])

In [27]:
np.random.seed(94)
b=np.random.randint(15,50,(7,8))
b

array([[33, 15, 18, 37, 44, 34, 31, 23],
       [31, 29, 48, 25, 47, 39, 39, 18],
       [30, 41, 26, 21, 28, 29, 17, 38],
       [49, 47, 16, 15, 48, 22, 44, 35],
       [23, 30, 25, 34, 42, 16, 39, 35],
       [45, 45, 21, 45, 37, 48, 23, 47],
       [30, 37, 37, 17, 45, 24, 44, 39]])

In [28]:
b[-4] #4th row from bottom

array([49, 47, 16, 15, 48, 22, 44, 35])

In [29]:
b[2]

array([30, 41, 26, 21, 28, 29, 17, 38])

In [30]:
b[:,7] #7th column

array([23, 18, 38, 35, 35, 47, 39])

In [31]:
b[-2,5]

48

In [32]:
b[-4,-1]

35

In [33]:
b[3,1]

47

In [34]:
b[1:5,1:5]

array([[29, 48, 25, 47],
       [41, 26, 21, 28],
       [47, 16, 15, 48],
       [30, 25, 34, 42]])

In [35]:
b[1:5]

array([[31, 29, 48, 25, 47, 39, 39, 18],
       [30, 41, 26, 21, 28, 29, 17, 38],
       [49, 47, 16, 15, 48, 22, 44, 35],
       [23, 30, 25, 34, 42, 16, 39, 35]])

array[row_start : row-end : row-step ,col_start : col-end : col_step]

In [36]:
b

array([[33, 15, 18, 37, 44, 34, 31, 23],
       [31, 29, 48, 25, 47, 39, 39, 18],
       [30, 41, 26, 21, 28, 29, 17, 38],
       [49, 47, 16, 15, 48, 22, 44, 35],
       [23, 30, 25, 34, 42, 16, 39, 35],
       [45, 45, 21, 45, 37, 48, 23, 47],
       [30, 37, 37, 17, 45, 24, 44, 39]])

In [37]:
b[3:7,2:5]

array([[16, 15, 48],
       [25, 34, 42],
       [21, 45, 37],
       [37, 17, 45]])

In [47]:
b[1:7,1:7]

array([[29, 48, 25, 47, 39, 39],
       [41, 26, 21, 28, 29, 17],
       [47, 16, 15, 48, 22, 44],
       [30, 25, 34, 42, 16, 39],
       [45, 21, 45, 37, 48, 23],
       [37, 37, 17, 45, 24, 44]])

In [61]:
b[-6::1,-7:-1:1]

array([[29, 48, 25, 47, 39, 39],
       [41, 26, 21, 28, 29, 17],
       [47, 16, 15, 48, 22, 44],
       [30, 25, 34, 42, 16, 39],
       [45, 21, 45, 37, 48, 23],
       [37, 37, 17, 45, 24, 44]])

In [62]:
b

array([[33, 15, 18, 37, 44, 34, 31, 23],
       [31, 29, 48, 25, 47, 39, 39, 18],
       [30, 41, 26, 21, 28, 29, 17, 38],
       [49, 47, 16, 15, 48, 22, 44, 35],
       [23, 30, 25, 34, 42, 16, 39, 35],
       [45, 45, 21, 45, 37, 48, 23, 47],
       [30, 37, 37, 17, 45, 24, 44, 39]])

31,48,47,39
49,16,48,44
45,21,37,23
find?

In [68]:
b[b>40]

array([44, 48, 47, 41, 49, 47, 48, 44, 42, 45, 45, 45, 48, 47, 45, 44])

In [69]:
np.where(b>40)

(array([0, 1, 1, 2, 3, 3, 3, 3, 4, 5, 5, 5, 5, 5, 6, 6], dtype=int64),
 array([4, 2, 4, 1, 0, 1, 4, 6, 4, 0, 1, 3, 5, 7, 4, 6], dtype=int64))